// src/app/layout.js
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Travel Planner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header className="bg-white shadow-md">
          <nav className="container mx-auto px-6 py-3 flex justify-between items-center">
            <Link href="/" className="text-xl font-bold text-gray-800">AI 여행 플래너</Link>
            <div>
              {/* '채팅' 링크를 홈('/')으로 변경 */}
              <Link href="/" className="px-4 py-2 text-gray-600 hover:text-blue-500">채팅</Link>
              <Link href="/map" className="px-4 py-2 text-gray-600 hover:text-blue-500">지도</Link>
            </div>
          </nav>
        </header>
        <main className="bg-gray-50">{children}</main>
      </body>
    </html>
  );
}
